name: Visual Regression

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Номер Pull Request'
        required: true
      task_id:
        description: 'ID задачи (например BLOCK2-1)'
        required: true

env:
  NODE_VERSION: 22

jobs:
  visual-regression:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout test config only
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            tests/
            playwright.config.ts
            package.json
            package-lock.json
            tsconfig.json
            scripts/
            .github/

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for deployed preview
        run: node tests/wait-for-url.js "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-${{ github.event.inputs.pr_number }}/"

      - name: Run Playwright tests
        env:
          PR_NUMBER: ${{ github.event.inputs.pr_number }}
          TASK_ID: ${{ github.event.inputs.task_id }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          CI: true
        run: |
          npx playwright install --with-deps
          npx playwright test

      - name: Upload diffs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-diff-${{ github.event.inputs.task_id }}
          path: test-results/
